# Generated by Django 4.1.1 on 2022-09-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachments',
            options={'verbose_name': 'Вкладення', 'verbose_name_plural': 'Вкладення'},
        ),
        migrations.AlterField(
            model_name='mail',
            name='attachments',
            field=models.ManyToManyField(null=True, to='mass_mail.attachments', verbose_name='Вкладення'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='bcc',
            field=models.ManyToManyField(null=True, to='mass_mail.bcc', verbose_name='Прихована копія'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='cc',
            field=models.ManyToManyField(null=True, to='mass_mail.cc', verbose_name='Копія'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='replay_to',
            field=models.ManyToManyField(null=True, to='mass_mail.replay_to', verbose_name='Адреси для відповіді'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='to',
            field=models.ManyToManyField(null=True, to='mass_mail.to', verbose_name='Отримувач'),
        ),
    ]
